In [ ]:
# importando a biblioteca pandas e os arquivos Csv
import pandas as pd
import numpy as np
import numpy as np
df_clientes = pd.read_csv('clientes.csv', sep=';')
df_itens_pedidos = pd.read_csv('Itens_pedidos.csv', sep=';')
df_pedidos = pd.read_csv('Pedidos.csv',sep=';')
df_produtos = pd.read_csv('Produtos.csv',sep=';')
df_vendedores = pd.read_csv('Vendedores.csv',sep=';')
display(df_clientes)
display(df_itens_pedidos)
display(df_pedidos)
display(df_produtos)
display(df_vendedores)

     cliente_id  nome_cliente          cidade  uf       segmento data_cadastro
0             1  Cliente 0001         Goiânia  GO  Média Empresa    17/07/2024
1             2  Cliente 0002       São Paulo  SP  Pessoa Física    29/07/2023
2             3  Cliente 0003    Porto Alegre  RS  Média Empresa    14/05/2025
3             4  Cliente 0004        Brasília  DF  Pessoa Física    23/03/2024
4             5  Cliente 0005          Santos  SP  Média Empresa    24/02/2023
..          ...           ...             ...  ..            ...           ...
345         346  Cliente 0346         Goiânia  GO  Pessoa Física    10/07/2023
346         347  Cliente 0347        Curitiba  PR  Média Empresa    02/02/2025
347         348  Cliente 0348  Belo Horizonte  MG  Média Empresa    24/02/2026
348         349  Cliente 0349   Caxias do Sul  RS  Média Empresa    08/09/2023
349         350  Cliente 0350        Londrina  PR  Média Empresa    16/05/2025

[350 rows x 6 columns]

      pedido_id  produto_id  quantidade preco_unitario desconto_pct
0         10002          20         1.0         474,99            0
1         10002           9         1.0        1485,58         0,05
2         10003          14         1.0         363,22         0,15
3         10003          19         1.0         268,92         0,15
4         10003          10         1.0         885,93         0,05
...         ...         ...         ...            ...          ...
5512      11856           3         2.0         506,79         0,05
5513      12055          20         2.0         474,99            0
5514      10989           3         1.0         533,46            0
5515      11609          15         1.0          42,46            0
5516      11596           6         1.0        1136,97            0

[5517 rows x 5 columns]

,pedido_id,data_pedido,cliente_id,vendedor_id,canal,status,forma_pagamento
0,10002,29/11/2025,291,5,Loja Física,Cancelado,PIX
1,10003,13/05/2026,311,4,Televendas,Concluído,Cartão de crédito
2,10004,26/02/2025,4,2,Marketplace,Em separação,PIX
3,10005,24/08/2025,257,5,Marketplace,Concluído,Cartão de crédito
4,10006,29/11/2025,88,5,Televendas,Cancelado,Boleto
...,...,...,...,...,...,...,...
2200,11706,05/04/2025,153,5,Loja Física,Concluído,Boleto
2201,11643,23/01/2025,295,1,Marketplace,Concluído,Cartão de crédito
2202,11875,17/04/2025,93,2,Televendas,Concluído,Boleto
2203,11813,25/07/2025,94,2,Loja Física,Concluído,Boleto
2204,11001,31/08/2025,78,1,Marketplace,Concluído,PIX

   produto_id           produto    categoria custo_unitario preco_lista
0        1,00    Fone Bluetooth  Eletrônicos         783,66     1346,87
1        2,00     Mouse sem fio          NaN         872,13     1430,53
2        3,00  Teclado mecânico  Eletrônicos         328,15      533,46
3        4,00        Monitor 24  Eletrônicos         205,64      344,83
4        5,00         Webcam HD  Eletrônicos         215,78      284,90
5        6,00         Cafeteira         Casa         763,62     1136,97
6        7,00    Liquidificador         Casa         690,62     1120,99
7        8,00         Luminária         Casa         729,97     1313,47
8        9,00   Jogo de panelas         Casa         877,55     1563,77
9       10,00        Ventilador         Casa         559,17      932,56
10      11,00           Caderno          NaN          41,16       76,31
11      12,00        Caneta kit    Papelaria         749,58     1067,28
12      13,00           Mochila    Papelaria         177,13      302,32
13      14,00            Agenda    Papelaria         290,52      427,32
14      15,00       Organizador    Papelaria          23,39       42,46
15      16,00           SSD 1TB  Informática         517,50      781,69
16      17,00       Memória RAM  Informática         143,13      237,82
17      18,00           Hub USB          NaN          45,04       78,14
18      19,00          Notebook  Informática         207,75      316,38
19      20,00  Suporte notebook  Informática         318,67      474,99

   vendedor_id      vendedor   equipe
0            1     Ana Costa  Interno
1            2    Bruno Lima  Externo
2            3   Carla Souza  Interno
3            4   Diego Alves  Digital
4            5  Elaine Rocha  Externo
5            6   Felipe Melo  Digital

In [67]:
# obtendo informações das tabelas 
df_clientes.info()
df_itens_pedidos.info()
df_pedidos.info()
df_produtos.info()
df_vendedores.info()

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cliente_id     350 non-null    int64
 1   nome_cliente   350 non-null    str
 2   cidade         340 non-null    str
 3   uf             350 non-null    str
 4   segmento       350 non-null    str
 5   data_cadastro  350 non-null    str
dtypes: int64(1), str(5)
memory usage: 16.5 KB
<class 'pandas.DataFrame'>
RangeIndex: 5517 entries, 0 to 5516
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pedido_id       5517 non-null   int64
 1   produto_id      5517 non-null   int64
 2   quantidade      5505 non-null   float64
 3   preco_unitario  5517 non-null   str
 4   desconto_pct    5517 non-null   str
dtypes: float64(1), int64(2), str(2)
memory usage: 215.6 KB
<class 'pandas.DataFrame'>
RangeIndex: 2205 entries, 0 to 2204
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pedido_id        2205 non-null   int64
 1   data_pedido      2205 non-null   str
 2   cliente_id       2205 non-null   int64
 3   vendedor_id      2205 non-null   int64
 4   canal            2197 non-null   str
 5   status           2205 non-null   str
 6   forma_pagamento  2205 non-null   str
dtypes: int64(3), str(4)
memory usage: 120.7 KB
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   produto_id      20 non-null     str
 1   produto         20 non-null     str
 2   categoria       17 non-null     str
 3   custo_unitario  20 non-null     str
 4   preco_lista     20 non-null     str
dtypes: str(5)
memory usage: 932.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vendedor_id  6 non-null      int64
 1   vendedor     6 non-null      str
 2   equipe       6 non-null      str
dtypes: int64(1), str(2)
memory usage: 276.0 bytes

In [68]:
#descrição dos produtos
from IPython.display import display

display(df_clientes.describe(include='all'))
display(df_itens_pedidos.describe(include='all'))
display(df_pedidos.describe(include='all'))
display(df_produtos.describe(include='all'))
display(df_vendedores.describe(include='all'))

,cliente_id,nome_cliente,cidade,uf,segmento,data_cadastro
count,350.000000,350,340,350,350,350
unique,NaN,350,24,10,4,313
top,NaN,Cliente 0001,Rio de Janeiro,RJ,Média Empresa,14/06/2023
freq,NaN,1,26,49,119,3
mean,175.500000,NaN,NaN,NaN,NaN,NaN
std,101.180532,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN
25%,88.250000,NaN,NaN,NaN,NaN,NaN
50%,175.500000,NaN,NaN,NaN,NaN,NaN
75%,262.750000,NaN,NaN,NaN,NaN,NaN
max,350.000000,NaN,NaN,NaN,NaN,NaN

           pedido_id   produto_id   quantidade preco_unitario desconto_pct
count    5517.000000  5517.000000  5505.000000           5517         5517
unique           NaN          NaN          NaN             80            5
top              NaN          NaN          NaN         932,56            0
freq             NaN          NaN          NaN            155         2742
mean    11101.556824    10.487040     1.750045            NaN          NaN
std       640.309727     5.766774     1.004176            NaN          NaN
min     10002.000000     1.000000     1.000000            NaN          NaN
25%     10549.000000     5.000000     1.000000            NaN          NaN
50%     11097.000000    10.000000     1.000000            NaN          NaN
75%     11662.000000    16.000000     2.000000            NaN          NaN
max     12201.000000    20.000000     5.000000            NaN          NaN

,pedido_id,data_pedido,cliente_id,vendedor_id,canal,status,forma_pagamento
count,2205.000000,2205,2205.000000,2205.000000,2197,2205,2205
unique,NaN,588,NaN,NaN,4,4,4
top,NaN,22/01/2026,NaN,NaN,Televendas,Concluído,Cartão de débito
freq,NaN,11,NaN,NaN,602,1809,570
mean,11102.647619,NaN,175.315193,3.488889,NaN,NaN,NaN
std,635.141325,NaN,99.711744,1.711096,NaN,NaN,NaN
min,10002.000000,NaN,1.000000,1.000000,NaN,NaN,NaN
25%,10553.000000,NaN,90.000000,2.000000,NaN,NaN,NaN
50%,11103.000000,NaN,175.000000,4.000000,NaN,NaN,NaN
75%,11653.000000,NaN,261.000000,5.000000,NaN,NaN,NaN
max,12201.000000,NaN,350.000000,6.000000,NaN,NaN,NaN

       produto_id         produto categoria custo_unitario preco_lista
count          20              20        17             20          20
unique         20              20         4             20          20
top          1,00  Fone Bluetooth      Casa         783,66     1346,87
freq            1               1         5              1           1

        vendedor_id   vendedor   equipe
count      6.000000          6        6
unique          NaN          6        3
top             NaN  Ana Costa  Interno
freq            NaN          1        2
mean       3.500000        NaN      NaN
std        1.870829        NaN      NaN
min        1.000000        NaN      NaN
25%        2.250000        NaN      NaN
50%        3.500000        NaN      NaN
75%        4.750000        NaN      NaN
max        6.000000        NaN      NaN

In [ ]:
# Nulos e duplicatas clientes
display(df_clientes.isnull().sum())
df_analise=df_clientes[df_clientes['cidade'].isnull()]
display(df_analise)

# Proporção de cidades ausentes na base
df_analise=(df_clientes['cidade'].isnull().sum() / len(df_clientes)) * 100
display(df_analise)
display(df_clientes.duplicated().sum())

cliente_id        0
nome_cliente      0
cidade           10
uf                0
segmento          0
data_cadastro     0
dtype: int64

     cliente_id  nome_cliente cidade  uf         segmento data_cadastro
29           30  Cliente 0030    NaN  PR  Pequena Empresa    25/03/2024
30           31  Cliente 0031    NaN  MG    Pessoa Física    07/04/2023
32           33  Cliente 0033    NaN  PR  Pequena Empresa    20/02/2025
70           71  Cliente 0071    NaN  SC    Pessoa Física    30/08/2024
149         150  Cliente 0150    NaN  RS  Pequena Empresa    08/05/2023
150         151  Cliente 0151    NaN  SP  Pequena Empresa    11/04/2026
224         225  Cliente 0225    NaN  RJ    Pessoa Física    03/05/2023
242         243  Cliente 0243    NaN  SP  Pequena Empresa    29/06/2026
264         265  Cliente 0265    NaN  GO  Pequena Empresa    01/02/2023
297         298  Cliente 0298    NaN  MG    Média Empresa    24/10/2025

np.float64(2.857142857142857)

np.int64(0)

In [ ]:
# Nulos e duplicatas itens pedidos
display(df_itens_pedidos.isnull().sum())
df_analise=df_itens_pedidos[df_itens_pedidos['quantidade'].isnull()]
display(df_analise)

# Proporção de quantidades ausentes na base 
df_analise=(df_itens_pedidos['quantidade'].isnull().sum() / len(df_itens_pedidos))*100
display(df_analise)
display(df_clientes.duplicated().sum())

pedido_id          0
produto_id         0
quantidade        12
preco_unitario     0
desconto_pct       0
dtype: int64

      pedido_id  produto_id  quantidade preco_unitario desconto_pct
240       10091          16         NaN         781,69            0
849       10333          20         NaN         427,49          0,1
2000      10797          16         NaN         781,69            0
2019      10804          15         NaN          42,46            0
2566      11016          10         NaN         932,56            0
2737      11089           9         NaN        1485,58         0,05
3007      11194           3         NaN         480,11          0,1
3760      11516          14         NaN         427,32            0
4091      11646           7         NaN        1064,94         0,05
4101      11651           4         NaN         344,83            0
5079      12038           4         NaN         344,83            0
5330      12133          18         NaN          78,14            0

np.float64(0.2175095160413268)

np.int64(0)

In [ ]:
# Nulos e duplicatas pedidos
display(df_pedidos.isnull().sum())
df_analise=df_pedidos[df_pedidos['canal'].isnull()]
display(df_analise)

# Proporção de quantidades ausentes na base 
df_analise=(df_pedidos['canal'].isnull().sum() / len(df_pedidos))*100
display(df_analise)
display(df_clientes.duplicated().sum())

pedido_id          0
data_pedido        0
cliente_id         0
vendedor_id        0
canal              8
status             0
forma_pagamento    0
dtype: int64

,pedido_id,data_pedido,cliente_id,vendedor_id,canal,status,forma_pagamento
149,10151,21/03/2026,81,1,NaN,Concluído,PIX
362,10364,15/09/2025,172,5,NaN,Concluído,Cartão de crédito
607,10609,02/07/2026,60,1,NaN,Concluído,Boleto
779,10781,06/06/2025,91,2,NaN,Concluído,Cartão de crédito
1386,11388,25/04/2025,313,2,NaN,Concluído,PIX
1539,11541,12/12/2025,146,3,NaN,Concluído,Cartão de débito
1665,11667,14/05/2026,70,3,NaN,Devolvido,Boleto
1814,11816,09/08/2026,107,6,NaN,Cancelado,Boleto

np.float64(0.36281179138321995)

np.int64(0)

In [ ]:
# Nulos e duplicatas vendedores
display(df_vendedores.isnull().sum())
display(df_clientes.duplicated().sum())

vendedor_id    0
vendedor       0
equipe         0
dtype: int64

np.int64(0)

In [ ]:
# Padronizando strings 
display(df_pedidos)
df_pedidos["status"]=df_pedidos["status"].str.replace("Em separação","Em processamento")
display(df_pedidos)

,pedido_id,data_pedido,cliente_id,vendedor_id,canal,status,forma_pagamento
0,10002,29/11/2025,291,5,Loja Física,Cancelado,PIX
1,10003,13/05/2026,311,4,Televendas,Concluído,Cartão de crédito
2,10004,26/02/2025,4,2,Marketplace,Em separação,PIX
3,10005,24/08/2025,257,5,Marketplace,Concluído,Cartão de crédito
4,10006,29/11/2025,88,5,Televendas,Cancelado,Boleto
...,...,...,...,...,...,...,...
2200,11706,05/04/2025,153,5,Loja Física,Concluído,Boleto
2201,11643,23/01/2025,295,1,Marketplace,Concluído,Cartão de crédito
2202,11875,17/04/2025,93,2,Televendas,Concluído,Boleto
2203,11813,25/07/2025,94,2,Loja Física,Concluído,Boleto
2204,11001,31/08/2025,78,1,Marketplace,Concluído,PIX

,pedido_id,data_pedido,cliente_id,vendedor_id,canal,status,forma_pagamento
0,10002,29/11/2025,291,5,Loja Física,Cancelado,PIX
1,10003,13/05/2026,311,4,Televendas,Concluído,Cartão de crédito
2,10004,26/02/2025,4,2,Marketplace,Em processamento,PIX
3,10005,24/08/2025,257,5,Marketplace,Concluído,Cartão de crédito
4,10006,29/11/2025,88,5,Televendas,Cancelado,Boleto
...,...,...,...,...,...,...,...
2200,11706,05/04/2025,153,5,Loja Física,Concluído,Boleto
2201,11643,23/01/2025,295,1,Marketplace,Concluído,Cartão de crédito
2202,11875,17/04/2025,93,2,Televendas,Concluído,Boleto
2203,11813,25/07/2025,94,2,Loja Física,Concluído,Boleto
2204,11001,31/08/2025,78,1,Marketplace,Concluído,PIX

In [ ]:

# Conversão clientes
display(df_clientes.info())
df_clientes["data_cadastro"]=pd.to_datetime(df_clientes["data_cadastro"],dayfirst=True)
display(df_clientes.info())

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cliente_id     350 non-null    int64
 1   nome_cliente   350 non-null    str
 2   cidade         340 non-null    str
 3   uf             350 non-null    str
 4   segmento       350 non-null    str
 5   data_cadastro  350 non-null    datetime64[us]
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 16.5 KB

None

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cliente_id     350 non-null    int64
 1   nome_cliente   350 non-null    str
 2   cidade         340 non-null    str
 3   uf             350 non-null    str
 4   segmento       350 non-null    str
 5   data_cadastro  350 non-null    datetime64[us]
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 16.5 KB

None

In [ ]:
# Conversão itens pedidos
display(df_itens_pedidos.info())
df_itens_pedidos["quantidade"]=(
    df_itens_pedidos["quantidade"].astype("Int64"))

df_itens_pedidos['preco_unitario'] = pd.to_numeric(
    df_itens_pedidos['preco_unitario'].str.replace(',', '.', regex=False),
    errors='raise'
)

df_itens_pedidos['desconto_pct'] = pd.to_numeric(
    df_itens_pedidos['desconto_pct']
        .str.replace(',', '.', regex=False)
        .replace('sem desconto', '0'),
    errors='raise'
)


df_itens_pedidos.info()

display(df_itens_pedidos.dtypes)
display(df_itens_pedidos.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 5517 entries, 0 to 5516
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pedido_id       5517 non-null   int64
 1   produto_id      5517 non-null   int64
 2   quantidade      5505 non-null   Int64
 3   preco_unitario  5517 non-null   float64
 4   desconto_pct    5517 non-null   float64
dtypes: Int64(1), float64(2), int64(2)
memory usage: 221.0 KB

None

AttributeError: Can only use .str accessor with string values, not floating

In [ ]:
# Conversão pedidos
df_pedidos["data_pedido"]=pd.to_datetime(df_pedidos["data_pedido"],dayfirst=True)
display(df_pedidos.info())

<class 'pandas.DataFrame'>
RangeIndex: 2205 entries, 0 to 2204
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pedido_id        2205 non-null   int64
 1   data_pedido      2205 non-null   datetime64[us]
 2   cliente_id       2205 non-null   int64
 3   vendedor_id      2205 non-null   int64
 4   canal            2197 non-null   str
 5   status           2205 non-null   str
 6   forma_pagamento  2205 non-null   str
dtypes: datetime64[us](1), int64(3), str(3)
memory usage: 120.7 KB

None

In [ ]:
# Conversão produtos
display(df_produtos.info())
df_produtos['produto_id'] = pd.to_numeric(
    df_itens_pedidos['produto_id'],
    errors='raise'
)

df_produtos['custo_unitario']=pd.to_numeric(
    df_produtos['custo_unitario'].str.replace(',','.',regex=False),
    errors='raise'

)

df_produtos['preco_lista']=pd.to_numeric(
    df_produtos['preco_lista'].str.replace(',','.',regex=False),
    errors='raise'

)
display(df_produtos.info())

In [ ]:
# juntando tabelas 
# Junta df_itens_pedidos usando pedido_id

df_analise=df_itens_pedidos.merge(
                    df_pedidos,
                    on='pedido_id',
                    how='inner')

df_analise=df_analise.merge(
                    df_produtos,
                    on='produto_id',
                    how='left')

df_analise=df_analise.merge(
    df_clientes,
    on='cliente_id',
    how='left'
      )

df_analise=df_analise.merge(
    df_vendedores,
    on='vendedor_id',
    how='left'
)
display(df_analise)

,pedido_id,produto_id,quantidade,preco_unitario,desconto_pct,data_pedido,cliente_id,vendedor_id,canal,status,...,categoria,custo_unitario,preco_lista,nome_cliente,cidade,uf,segmento,data_cadastro,vendedor,equipe
0,10002,20,1,474.99,0.00,2025-11-29,291,5,Loja Física,Cancelado,...,Eletrônicos,"783,66","1346,87",Cliente 0291,Olinda,PE,Pequena Empresa,2024-04-16,Elaine Rocha,Externo
1,10002,9,1,1485.58,0.05,2025-11-29,291,5,Loja Física,Cancelado,...,NaN,"872,13","1430,53",Cliente 0291,Olinda,PE,Pequena Empresa,2024-04-16,Elaine Rocha,Externo
2,10003,14,1,363.22,0.15,2026-05-13,311,4,Televendas,Concluído,...,Eletrônicos,"328,15","533,46",Cliente 0311,Goiânia,GO,Média Empresa,2023-10-05,Diego Alves,Digital
3,10003,14,1,363.22,0.15,2026-05-13,311,4,Televendas,Concluído,...,Papelaria,"177,13","302,32",Cliente 0311,Goiânia,GO,Média Empresa,2023-10-05,Diego Alves,Digital
4,10003,19,1,268.92,0.15,2026-05-13,311,4,Televendas,Concluído,...,Eletrônicos,"205,64","344,83",Cliente 0311,Goiânia,GO,Média Empresa,2023-10-05,Diego Alves,Digital
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6983,12055,20,2,474.99,0.00,2026-03-08,293,1,Loja Física,Concluído,...,Eletrônicos,"783,66","1346,87",Cliente 0293,Olinda,PE,Média Empresa,2023-10-08,Ana Costa,Interno
6984,10989,3,1,533.46,0.00,2026-02-02,284,6,Loja Física,Concluído,...,Papelaria,"23,39","42,46",Cliente 0284,Belo Horizonte,MG,Pequena Empresa,2024-12-08,Felipe Melo,Digital
6985,10989,3,1,533.46,0.00,2026-02-02,284,6,Loja Física,Concluído,...,NaN,"45,04","78,14",Cliente 0284,Belo Horizonte,MG,Pequena Empresa,2024-12-08,Felipe Melo,Digital
6986,11609,15,1,42.46,0.00,2025-07-03,24,2,Marketplace,Cancelado,...,Informática,"318,67","474,99",Cliente 0024,São Paulo,SP,Pequena Empresa,2025-04-01,Bruno Lima,Externo
6987,11596,6,1,1136.97,0.00,2026-06-26,209,3,Loja Física,Concluído,...,Informática,"143,13","237,82",Cliente 0209,Florianópolis,SC,Média Empresa,2026-07-13,Carla Souza,Interno

In [ ]:
# Pedidos de janeiro e outubro
display(df_pedidos.info())
janeiro=df_pedidos[df_pedidos['data_pedido'].dt.month==1]
outubro=df_pedidos[df_pedidos['data_pedido'].dt.month==10]

df_resultado=pd.concat([janeiro,outubro])
display(df_resultado)

# Mês que teve mais pedidos e quantos pedidos existem em cada um.
df_analise=df_resultado.groupby(df_resultado['data_pedido'].dt.month).size()
display(df_resultado)

# Analisar os status dos pedidos
status_pedidos=df_resultado['status'].value_counts()
display(status_pedidos)

# Quais vendedores recebem mais pedidos
analise_vendedores=df_resultado.groupby('vendedor_id').size()
display(analise_vendedores)

<class 'pandas.DataFrame'>
RangeIndex: 2205 entries, 0 to 2204
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pedido_id        2205 non-null   int64
 1   data_pedido      2205 non-null   datetime64[us]
 2   cliente_id       2205 non-null   int64
 3   vendedor_id      2205 non-null   int64
 4   canal            2197 non-null   str
 5   status           2205 non-null   str
 6   forma_pagamento  2205 non-null   str
dtypes: datetime64[us](1), int64(3), str(3)
memory usage: 120.7 KB

None

,pedido_id,data_pedido,cliente_id,vendedor_id,canal,status,forma_pagamento
17,10019,2026-01-16,284,1,Loja Física,Concluído,PIX
79,10081,2026-01-22,283,4,Loja Física,Concluído,PIX
81,10083,2025-01-17,107,5,E-commerce,Concluído,Cartão de débito
84,10086,2026-01-25,44,5,Marketplace,Concluído,Cartão de crédito
88,10090,2026-01-05,129,2,Televendas,Concluído,PIX
...,...,...,...,...,...,...,...
2079,12081,2025-10-25,173,3,Loja Física,Concluído,Boleto
2082,12084,2025-10-12,55,4,Televendas,Concluído,Boleto
2098,12100,2025-10-23,46,2,Televendas,Devolvido,Cartão de crédito
2129,12131,2025-10-26,83,2,E-commerce,Concluído,Cartão de crédito
2186,12188,2025-10-23,290,4,E-commerce,Concluído,PIX

,pedido_id,data_pedido,cliente_id,vendedor_id,canal,status,forma_pagamento
17,10019,2026-01-16,284,1,Loja Física,Concluído,PIX
79,10081,2026-01-22,283,4,Loja Física,Concluído,PIX
81,10083,2025-01-17,107,5,E-commerce,Concluído,Cartão de débito
84,10086,2026-01-25,44,5,Marketplace,Concluído,Cartão de crédito
88,10090,2026-01-05,129,2,Televendas,Concluído,PIX
...,...,...,...,...,...,...,...
2079,12081,2025-10-25,173,3,Loja Física,Concluído,Boleto
2082,12084,2025-10-12,55,4,Televendas,Concluído,Boleto
2098,12100,2025-10-23,46,2,Televendas,Devolvido,Cartão de crédito
2129,12131,2025-10-26,83,2,E-commerce,Concluído,Cartão de crédito
2186,12188,2025-10-23,290,4,E-commerce,Concluído,PIX

status
Concluído           289
Cancelado            26
Em processamento     17
Devolvido             9
Name: count, dtype: int64

vendedor_id
1    63
2    60
3    51
4    53
5    62
6    52
dtype: int64

In [ ]:

df_analise=df_itens_pedidos.merge(
    df_produtos,
    on='produto_id',
    how='left'
)

display(df_analise)

# Quantidade total vendida por categoria.
# Qreço médio dos itens por categoria.
categoria_analise=df_analise.groupby('categoria').agg(
    qtd_categoria=('quantidade','sum'),preco_medio=('preco_unitario','mean') )
display(categoria_analise)

# Categoria Com o maior faturamento.
df_analise['Faturamento']=df_analise['quantidade']*df_analise['preco_unitario']
df_analise=df_analise.groupby('categoria').agg(total_faturamento=('Faturamento','sum'))
df_analise=df_analise.sort_values(by='total_faturamento',ascending=False)
display(df_analise)

# Maior faturamento e menor faturamento
display(df_analise.head(1))
display(df_analise.tail(1))

,pedido_id,produto_id,quantidade,preco_unitario,desconto_pct,produto,categoria,custo_unitario,preco_lista
0,10002,20,1,474.99,0.00,Fone Bluetooth,Eletrônicos,"783,66","1346,87"
1,10002,9,1,1485.58,0.05,Mouse sem fio,NaN,"872,13","1430,53"
2,10003,14,1,363.22,0.15,Teclado mecânico,Eletrônicos,"328,15","533,46"
3,10003,14,1,363.22,0.15,Mochila,Papelaria,"177,13","302,32"
4,10003,19,1,268.92,0.15,Monitor 24,Eletrônicos,"205,64","344,83"
...,...,...,...,...,...,...,...,...,...
6973,12055,20,2,474.99,0.00,Fone Bluetooth,Eletrônicos,"783,66","1346,87"
6974,10989,3,1,533.46,0.00,Organizador,Papelaria,"23,39","42,46"
6975,10989,3,1,533.46,0.00,Hub USB,NaN,"45,04","78,14"
6976,11609,15,1,42.46,0.00,Suporte notebook,Informática,"318,67","474,99"
6977,11596,6,1,1136.97,0.00,Memória RAM,Informática,"143,13","237,82"

             qtd_categoria  preco_medio
categoria
Casa                  2437   650.180962
Eletrônicos           1948   516.731036
Informática           1945   410.629668
Papelaria             1987   755.864468

             total_faturamento
categoria
Casa                1597508.21
Papelaria           1477843.99
Eletrônicos          993893.09
Informática          816287.34

           total_faturamento
categoria
Casa              1597508.21

             total_faturamento
categoria
Informática          816287.34

In [ ]:
# Para resumo mensal
# Juntar itens dos pedidos com as datas e informações dos pedidos
df_completo = df_itens_pedidos.merge(
    df_pedidos,
    on='pedido_id',
    how='left'
)

# Adicionar as informações dos produtos
df_completo = df_completo.merge(
    df_produtos[['produto_id', 'categoria']],
    on='produto_id',
    how='left'
)

# Coluna Faturamento
df_completo['faturamento'] = (
    df_completo['quantidade'] * df_completo['preco_unitario']
)

# Coluna mes
df_completo['mes'] =df_completo['data_pedido'].dt.to_period('M')

tabela_mensal=pd.pivot_table(
    df_completo,
    index='mes',
    values='faturamento',
    aggfunc='sum'
)

tabela_mensal=tabela_mensal.sort_values(by='faturamento',ascending=False)
display(tabela_mensal)

# Mes com menor faturamento
display(tabela_mensal.tail(1))

In [ ]:
# Calculando a margem porcentual
display(df_produtos.info())
df_produtos['margem_pct']=(
    (df_produtos['preco_lista']-df_produtos['custo_unitario'])
    /df_produtos['preco_lista'])*100
display(df_produtos['margem_pct'])

# Classificar a margem
condicao=[
    df_produtos['margem_pct']<15,
    (df_produtos['margem_pct']>=15) &
    (df_produtos['margem_pct']<30),
    df_produtos['margem_pct']>=30
]

classificacoes=[
    'Margem Baixa',
    'Margem Média',
    'Margem Alta'
]

df_produtos['Classificação']=np.select(condicao,classificacoes,default='Verificar')
display(df_produtos)

In [13]:
# Obtendo a coluna quantidade
quantidade=df_itens_pedidos['quantidade'].dropna()

# Media da quantidade
media=np.mean(quantidade)

# Mediana da quantidade
mediana=np.median(quantidade)

# Desvio padrão da quantidade
desvio_padrao=np.std(quantidade)

print(f"Média:{media}\nMediana:{mediana}\nDesvio Padrão:{desvio_padrao}")

#Calcular os percentis

p25=np.percentile(quantidade,25)
p50=np.percentile(quantidade,50)
p75=np.percentile(quantidade,75)
p90=np.percentile(quantidade,90)

print('Percentil 25:', p25)
print('Percentil 50:', p50)
print('Percentil 75:', p75)
print('Percentil 90:', p90)

Média:1.7500454132606722
Mediana:1.0
Desvio Padrão:1.004084527404832
Percentil 25: 1.0
Percentil 50: 1.0
Percentil 75: 2.0
Percentil 90: 3.0

In [ ]:
# Comparando com My sql pedidos
print(len(df_pedidos))
display(df_pedidos)

print('Total de linhas:', len(df_pedidos))
print('IDs de pedidos únicos:', df_pedidos['pedido_id'].nunique())
print('IDs de pedidos duplicados:', df_pedidos['pedido_id'].duplicated().sum())


# Identificando a quantidade de registros repetidos 
duplicados = df_pedidos[
    df_pedidos['pedido_id'].duplicated(keep=False)
].sort_values('pedido_id')

display(duplicados)


# Apagando duplicatas 
df_pedidos_tratados = df_pedidos.drop_duplicates(
    subset='pedido_id',
    keep='first'
).copy()

# Validando resultado final

print('Linhas antes:', len(df_pedidos))
print('Linhas depois:', len(df_pedidos_tratados))
print(
    'IDs únicos depois:',
    df_pedidos_tratados['pedido_id'].nunique()
)
print(
    'IDs ainda duplicados:',
    df_pedidos_tratados['pedido_id'].duplicated().sum()
)

display(
    df_pedidos_tratados[
        df_pedidos_tratados['pedido_id'] == 11875
    ]
)

df_pedidos_tratados.to_csv(
    'Pedidos_tratados.csv',
    sep=';',
    index=False,
    encoding='utf-8-sig'
)

In [ ]:
# Comparando com My sql
print(len(df_produtos))
display(df_produtos)

# Total de linhas
print('Total de linhas:', len(df_produtos))

# IDs únicos
print('IDs únicos:', df_produtos['produto_id'].nunique())

# IDs duplicados
print(
    'IDs duplicados:',
    df_produtos['produto_id'].duplicated().sum()
)

# Valores ausentes por coluna
display(df_produtos.isnull().sum())

# Valores ausentes em categoria
display(df_produtos[df_produtos['categoria'].isnull()])

print(df_produtos.head(10))
print(df_produtos.columns.tolist())

# Conferir os produtos 1, 10 e 17 no Pandas
display(
    df_produtos[df_produtos['produto_id'].isin(['1,00', '10,00', '17,00'])]
)

# Os três produtos que realmente estão sem categoria

df_produtos = pd.read_csv('Produtos.csv', sep=';')

print(df_produtos.isnull().sum())

display(df_produtos[df_produtos['categoria'].isnull()])

# tratando valores nulos
df_produtos_analise = df_produtos.copy()

df_produtos_analise['categoria'] = (
    df_produtos_analise['categoria'].fillna('Não informado')
)

display(df_produtos_analise)

df_produtos_analise.to_csv(
    'Produtos_tratados.csv',
    sep=';',
    index=False,
    encoding='utf-8-sig'
)

In [ ]:
#comparando com My sql clientes
print(len(df_clientes))
display(df_clientes)


# Total de linhas
print('Total de linhas:', len(df_clientes))

# IDs únicos
print('IDs únicos:', df_clientes['cliente_id'].nunique())

# IDs duplicados
print(
    'IDs duplicados:',
    df_clientes['cliente_id'].duplicated().sum()
)

# Valores ausentes por coluna
display(df_clientes.isnull().sum())

# Quais clientes estão sem cidade
display(
    df_clientes.loc[
        df_clientes['cidade'].isnull(),
        ['cliente_id', 'nome_cliente', 'cidade', 'uf']
    ]
)

# Tratando valores nulo 
df_clientes_analise = df_clientes.copy()

df_clientes_analise['cidade'] = (
    df_clientes_analise['cidade'].fillna('Não informado')
)
display(df_clientes_analise)

df_clientes_analise.to_csv(
    'Clientes_tratados.csv',
    sep=';',
    index=False,
    encoding='utf-8-sig'
)

In [ ]:
# Comparando com My sql vendedores
print(len(df_vendedores))
display(df_vendedores)

# Total de linhas
print('Total de linhas:', len(df_vendedores))

# IDs únicos
print('IDs únicos:',df_vendedores['vendedor_id'].nunique())

# IDs duplicados
print(
    'IDs duplicados:',
    df_vendedores['vendedor_id'].duplicated().sum()
)

# Valores ausentes por coluna
display(df_vendedores.isnull().sum())

df_vendedores.to_csv(
    'Vendedores_tratados.csv',
    sep=';',
    index=False,
    encoding='utf-8-sig'
)

In [ ]:
#comparando com My sql itens pedidos 

# Total de linhas
print('Total de linhas:', len(df_itens_pedidos))

# Valores ausentes por coluna
print(df_itens_pedidos.isnull().sum())

# Quais pedidos estão sem quantidade
display(
    df_itens_pedidos.loc[
        df_itens_pedidos['quantidade'].isnull(),
    ]
)

# Tratando valores nulo 
df_analise_itens_pedidos = df_itens_pedidos.copy()
df_analise_itens_pedidos['quantidade']=(
    df_itens_pedidos['quantidade'].fillna('Não informado'))
display(df_analise_itens_pedidos)

analise=df_analise_itens_pedidos[
    df_analise_itens_pedidos['quantidade']=="Não informado"
]
display(analise)

df_analise_itens_pedidos.to_csv(
    'Itens_pedidos_tratados.csv',
    sep=';',
    index=False,
    encoding='utf-8-sig'
)

In [ ]:
#juntando tabelas 
juncao = df_itens_pedidos.merge(
    df_produtos,
    on='produto_id',
    how='inner',
    validate='many_to_one'
)
# Calcular receita e custo por item
juncao['receita_item'] = (
    juncao['quantidade'] * juncao['preco_unitario']
)

juncao['custo_item'] = (
    juncao['quantidade'] * juncao['custo_unitario']
)


# Somar os totais
receita_total = juncao['receita_item'].sum()
custo_total = juncao['custo_item'].sum()
lucro_total = receita_total - custo_total

print(f"Receita total: R$ {receita_total:,.2f}")
print(f"Custo total:   R$ {custo_total:,.2f}")
print(f"Lucro total:   R$ {lucro_total:,.2f}")
print(f"Linhas após junção: {len(juncao)}")